// Generated by gencpp from file jst_video/jst_image.msg
// DO NOT EDIT!


#ifndef JST_VIDEO_MESSAGE_JST_IMAGE_H
#define JST_VIDEO_MESSAGE_JST_IMAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace jst_video
{
template <class ContainerAllocator>
struct jst_image_
{
  typedef jst_image_<ContainerAllocator> Type;

  jst_image_()
    : header()
    , score(0.0)  {
    }
  jst_image_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , score(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::jst_video::jst_image_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jst_video::jst_image_<ContainerAllocator> const> ConstPtr;

}; // struct jst_image_

typedef ::jst_video::jst_image_<std::allocator<void> > jst_image;

typedef boost::shared_ptr< ::jst_video::jst_image > jst_imagePtr;
typedef boost::shared_ptr< ::jst_video::jst_image const> jst_imageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jst_video::jst_image_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jst_video::jst_image_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace jst_video

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'jst_video': ['/home/jst/share/project/ros_learning/convert_message_type/src/jst_video/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::jst_video::jst_image_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jst_video::jst_image_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jst_video::jst_image_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jst_video::jst_image_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jst_video::jst_image_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jst_video::jst_image_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jst_video::jst_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d3c143f3a5cce1f5cf4b251c8ca4af8f";
  }

  static const char* value(const ::jst_video::jst_image_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd3c143f3a5cce1f5ULL;
  static const uint64_t static_value2 = 0xcf4b251c8ca4af8fULL;
};

template<class ContainerAllocator>
struct DataType< ::jst_video::jst_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jst_video/jst_image";
  }

  static const char* value(const ::jst_video::jst_image_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jst_video::jst_image_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float32 score\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::jst_video::jst_image_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jst_video::jst_image_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jst_image_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jst_video::jst_image_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jst_video::jst_image_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JST_VIDEO_MESSAGE_JST_IMAGE_H
